# Generated by Django 2.2.28 on 2022-11-04 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='announcements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ex_employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=100)),
                ('PhoneNo', models.CharField(default='None', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Salary_mgmt',
            fields=[
                ('AC_No', models.CharField(default='None', max_length=200, primary_key=True, serialize=False)),
                ('IFSC', models.CharField(default='None', max_length=200)),
                ('Bank_name', models.CharField(default='None', max_length=200)),
                ('Gross_Sal', models.IntegerField(default=0)),
                ('Ded_amt', models.IntegerField(default=0)),
                ('Desc', models.CharField(default='None', max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='user.png', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reason', models.CharField(default='None', max_length=20)),
                ('No_of_days', models.IntegerField(default=0)),
                ('From', models.DateTimeField(default=django.utils.timezone.now)),
                ('To', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_details',
            fields=[
                ('Emp_id', models.CharField(default='None', max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Enter name', max_length=100)),
                ('PhoneNo', models.CharField(default='Enter phone number', max_length=100)),
                ('Designation', models.CharField(default='None', max_length=100)),
                ('Dept', models.CharField(default='None', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Duty_Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Month', models.CharField(default='None', max_length=20)),
                ('Time_in', models.TimeField(default='00:00')),
                ('Time_out', models.TimeField(default='00:00')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No_of_Days_Punched_in', models.IntegerField(default=0)),
                ('No_of_Duty_Days', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
