# Generated by Django 2.2.28 on 2022-11-04 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcements',
            options={'verbose_name_plural': 'Announcements'},
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name_plural': 'Attendance'},
        ),
        migrations.AlterModelOptions(
            name='duty_schedule',
            options={'verbose_name_plural': 'Duty_Schedules'},
        ),
        migrations.AlterModelOptions(
            name='employee_details',
            options={'verbose_name_plural': 'Employee_details'},
        ),
        migrations.AlterModelOptions(
            name='ex_employee',
            options={'verbose_name_plural': 'Ex_Employees'},
        ),
        migrations.AlterModelOptions(
            name='leave',
            options={'verbose_name_plural': 'Leave'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='salary_mgmt',
            options={'verbose_name_plural': 'Salary_mgmt'},
        ),
    ]
