# Generated by Django 2.2.28 on 2022-11-10 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_auto_20221110_0737'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deductions',
            options={'verbose_name_plural': 'Deductions'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='jobs',
            options={'verbose_name_plural': 'Jobs'},
        ),
    ]
